Repository zcmagda/gizmo, pull requests merged in 2019-04, with the labels that each got.

#9 Added possibility to gracefully shutdown server
  README.md
  build.gradle
  src/main/resources/application.properties
Labels: enhancement, invalid

#7 Added custom banner
  src/main/resources/banner.txt
Labels: enhancement

#8 Added editorconfig
  .editorconfig
  src/main/java/to/gizmo/Greeting.java
  src/main/java/to/gizmo/GreetingController.java
Labels: enhancement

#11 Ladies and Gentelmen, It's Bootstrap time
  .gitignore
  README.md
  build.gradle
  src/main/java/to/gizmo/Greeting.java
  src/main/java/to/gizmo/GreetingController.java
  src/main/java/to/gizmo/controllers/GizmoController.java
  src/main/java/to/gizmo/controllers/RegisterController.java
  src/main/java/to/gizmo/entities/User.java
  src/main/resources/application.properties
  src/main/resources/static/bootstrap.min.css
  src/main/resources/static/bootstrap.min.js
  src/main/resources/static/jquery-3.3.1.min.js
  src/main/resources/static/style.css
  src/main/resources/styles/_body.scss
  src/main/resources/styles/style.scss
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
Labels: TEST PLEASE, enhancement
